### ISSUE TITLE
install fail帮忙指点下

### ISSUE THREAD

**Issue by yanminmin** [bailichen/ImitateWeixinApp#63]
^
In file included from ../fsevents.cc:73:
../src/constants.cc:102:11: error: no matching member function for call to
      'Set'
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModifie...
  ~~~~~~~~^~~
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3547:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3550:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32...
                                    ^
In file included from ../fsevents.cc:73:
../src/constants.cc:103:11: error: no matching member function for call to
      'Set'
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderI...
  ~~~~~~~~^~~
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3547:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3550:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32...
                                    ^
In file included from ../fsevents.cc:73:
../src/constants.cc:104:11: error: no matching member function for call to
      'Set'
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeO...
  ~~~~~~~~^~~
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3547:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3550:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32...
                                    ^
In file included from ../fsevents.cc:73:
../src/constants.cc:105:11: error: no matching member function for call to
      'Set'
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMo...
  ~~~~~~~~^~~
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3547:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3550:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32...
                                    ^
In file included from ../fsevents.cc:73:
../src/constants.cc:106:11: error: no matching member function for call to
      'Set'
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile"...
  ~~~~~~~~^~~
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3547:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/yanminmin/Library/Caches/node-gyp/13.11.0/include/node/v8.h:3550:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32...
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.11.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64" "--napi_version=6" "--node_abi_napi=napi"
gyp ERR! cwd /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.11.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=6 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.11.0/bin/node" "/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents
node-pre-gyp ERR! node -v v13.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/13.11.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=6 --node_abi_napi=napi' (1)

> node-sass@4.11.0 install /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://npm.taobao.org/mirrors/node-sass/v4.11.0/darwin-x64-79_binding.node
Cannot download "https://npm.taobao.org/mirrors/node-sass/v4.11.0/darwin-x64-79_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/13.11.0/bin/node /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/13.11.0/bin/node',
gyp verb cli   '/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.11.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:171:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:171:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:171:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 13.11.0
gyp verb command install [ '13.11.0' ]
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb install input version string "13.11.0"
gyp verb install installing version: 13.11.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 13.11.0
gyp verb build dir attempting to create "build" dir: /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yanminmin/.node-gyp/13.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/yanminmin/.node-gyp/13.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/yanminmin/.node-gyp/13.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/yanminmin/go/src/github.com/vue-weixin/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/yanminmin/.node-gyp/13.11.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]

**Comment by yanminmin** [comment]
3408 verbose pkgid node-sass@4.11.0
3409 verbose cwd /Users/yanminmin/go/src/github.com/vue-weixin
3410 verbose Darwin 18.7.0
3411 verbose argv "/usr/local/Cellar/node/13.11.0/bin/node" "/usr/local/bin/npm" "install"
3412 verbose node v13.11.0
3413 verbose npm  v6.13.7
3414 error code ELIFECYCLE
3415 error errno 1
3416 error node-sass@4.11.0 postinstall: `node scripts/build.js`
3416 error Exit status 1
3417 error Failed at the node-sass@4.11.0 postinstall script.
3417 error This is probably not a problem with npm. There is likely additional logging output above.
3418 verbose exit [ 1, true ]
